source 'https://rubygems.org'
ruby '~> 3.3'

gem 'dry-validation'
gem 'rage-rb'
gem 'rufus-scheduler'
gem 'sequel'
gem 'sqlite3'

group :development, :test do
  gem 'rspec'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'webmock'
end
