source 'https://rubygems.org'
ruby '~> 3.3'

gem 'dry-configurable'
gem 'dry-initializer'
gem 'dry-struct'
gem 'dry-validation'
gem 'rage-rb'
gem 'roo' # read XTB .xlsx reports
gem 'rufus-scheduler'
gem 'sequel'
gem 'sqlite3'

group :development, :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'webmock'
end
